# Site settings
title: Doctor Batch
email: doc@torbat.ch
description: > 
  Doctor Batch
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://www.trilliumyogacenter.com" # the base hostname & protocol for your site
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: 
github_username:  doctorbatch

# Build settings
markdown: kramdown
